### ISSUE TITLE
Upgrading to 4.5.0 causes class cast exception 

### ISSUE THREAD

**Issue by davidbairdala** [kaleidos/grails-postgresql-extensions#72] opened 2015-08-08 04:34 UTC
I have a project that defines a domain object that has a Map property mapped to JsonMapType.

```groovy
class MyDomainClass implements Serializable {

    Map customFields = [:]

    static mapping = {
        customFields type: JsonMapType
    }
}
```

Under version 4.4.0 the following works:

```groovy
 def instance = MyDomainClass.get(params.id)
```

WIth version 4.5.0 the same code yields:

```
org.postgresql.util.PGobject cannot be cast to java.lang.String. Stacktrace follows:
Message: org.postgresql.util.PGobject cannot be cast to java.lang.String
    Line | Method
->>   49 | nullSafeGet in net.kaleidos.hibernate.usertype.JsonMapType
```

I am running against Postgres 9.3. Not sure if I'm doing something wrong, or if this is a bug introduced with 4.5.0.

Cheers, David.

**Comment by lmivan** [comment] 2015-08-14 19:26
I'll try to reproduce it and create a test for it and fix it. I need to dig a little bit to see what change introduced in the last version broke that.

**Comment by lmivan** [comment] 2015-08-15 20:29
I can't reproduce it from a test but I've been able to reproduce it from run-app. 
The change was introduced in #65 to fix this issue #66. 

I'm doing some test to fix this.

**Comment by eamon316** [comment] 2015-08-25 18:26
Just came across this today. Looks as if the following will fix 
```
String jsonString = ((PGobject)rs.getObject(names[0])).getValue();
```
as noted in [#66]

Is there a release planned to fix?

Thanks for all the effort +1 on the plugin

**Comment by lmivan** [comment] 2015-08-26 14:39
I'll try to publish a new version during this week.

**Comment by lmivan** [comment] 2015-09-08 07:31
I finally found the time to publish a new version. Fixed in `4.6.0` :-)

**Closed by lmivan** 2015-09-08 07:31 UTC

**Comment by gregopet** [comment] 2015-09-24 14:30
I tried this and got exceptions when the field was null; currently using 

```
        PGobject jsonObject = (PGobject)rs.getObject(names[0]);
        if (jsonObject != null) {
            return gson.fromJson(jsonObject.getValue(), userType);
        } else {
            return null;
        }
```

**Comment by lmivan** [comment] 2015-09-24 14:36
That's was fixed in #77 and released in `4.6.1`. Could you please try with that version?

**Comment by gregopet** [comment] 2015-09-24 15:27
I'm using the Grails 3 branch, I guess it wasn't ported to that branch yet?

**Comment by lmivan** [comment] 2015-09-24 20:42
Yes, you're right. The last changes have not been applied to the 3.x branch. You need to wait until next week...
